language: node_js

node_js:
    - "6"
    
env:
   global:
       GH_TOKEN : 
       REPOSITORY: 
    
branches:
    only:
        - master    

before_script:
    - npm install
    
script:
    - gulp build
    
after_script:
    - cd output
    - git init
    - git add .
    - git commit -m "Regenerated output"
    - git push --force --quiet "${REPOSITORY}" master:gh-pages > /dev/null 2>&1
